# Generated by Django 2.1 on 2020-06-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('articals', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='id')),
                ('authors', models.TextField(verbose_name='作者')),
                ('abstracts', models.TextField(verbose_name='摘要')),
                ('IndexTerms', models.TextField(verbose_name='标签')),
                ('keywords', models.TextField(verbose_name='关键字')),
                ('nodes', models.TextField(verbose_name='题目')),
                ('affiliations', models.TextField(verbose_name='作者单位')),
                ('inlinks', models.TextField(verbose_name='inlinks')),
                ('outlinks', models.TextField(verbose_name='outlinks')),
                ('GeneralTerms', models.TextField(verbose_name='GeneralTerms')),
            ],
            options={
                'db_table': 'paper',
            },
        ),
    ]
